### ISSUE TITLE
Exceptions when ToC is empty

### ISSUE THREAD

**Issue by Franz1960** [mikeobrien/TDMSReader#15]
When opening a TDMS file where the last segment has no content I got a KeyNotFoundException in File.cs#36. I fixed it by checking the presence of the keys before using them:

 ```
// apply previous metadata if available
if (prevMetaDataLookup.ContainsKey(m.Path[0]) && prevMetaDataLookup[m.Path[0]].ContainsKey(m.Path[1]))
{
    var prevMetaData = prevMetaDataLookup[m.Path[0]][m.Path[1]];
```

Then I got a OutOfMemoryException in ReadMetadata(Segment). Regex.Matches(..) got a huge value when reading the string length (_reader.ReadInt32()). I fixed it by skipping segments which have no content flags set in LoadMetadata(Reader):

```
foreach (var segment in segments)
{
    if (!(segment.TableOfContents.ContainsNewObjects || segment.TableOfContents.HasDaqMxData || segment.TableOfContents.HasMetaData || segment.TableOfContents.HasRawData)) {
        continue;
    }
```

Find the changed File.cs in this ZIP archive:

[File.cs.zip](https://github.com/mikeobrien/TDMSReader/files/256793/File.cs.zip)

Thanks for your excellent work!

Cheers,
Franz

**Comment by mikeobrien** [comment]
Merged in 0c5ea9d58b4a73958d3fee5bb99992518785689b and pushed to nuget, thx!
