### ISSUE TITLE
How to write Tdms file with c#?

### ISSUE THREAD

**Issue by lingfei87** [mikeobrien/TDMSReader#17]
Hello, your code is very helpful to me and i am thank for that. But i have  need to write tdms file with c# now. Do you have some idea for that ? It is best that some sample code for me . Thank you !

**Comment by mikeobrien** [comment]
There is some sample code here in the readme:

https://github.com/mikeobrien/TDMSReader

You can also check out the tests for more examples:

https://github.com/mikeobrien/TDMSReader/tree/master/src/Tests

HTH
