### ISSUE TITLE
Channel Metadata is read but most entries are not exposed in Channel properties.

### ISSUE THREAD

**Issue by DEIbb** [mikeobrien/TDMSReader#19]
Channel Metadata is read by reader but not exposed in Channel properties.
They are possibly filtered in File.LoadChannels.  I have run out of time and have not determined why all read attributes do not get exposed to Channel Properties.  The sporadic channel properties issue was not found in initial testing.  This issue occurs on every file and is not hard to reproduce.

Reader Line 83:
                metadata.Properties = new Dictionary<string, object>();
                for (var y = 0; y < propertyCount; y++)
                {
                    var key = _reader.ReadLengthPrefixedString();
                    var value = _reader.Read(_reader.ReadInt32());
                    metadata.Properties[key] = value;
>>> TRACEPOINT {key}={value}  {metadata.Path[0]} {metadata.Path[1]} >>>
                }
                metadatas.Add(metadata);

loads many Waveform" "BOP5-CWP1-MOH" metadata entries:

"unit_string"=""  "Waveform" "BOP5-CWP1-MOH"
"NI_CM_AssetNodeId"="57d6c4febaa884470461047f"  "Waveform" "BOP5-CWP1-MOH"
"NI_CM_AssetName"="Duke Energy|Smith|Power Block 5|PB5|Circ Water Pump 5A|Motor|BOP5-CWP1-MOH"  "Waveform" "BOP5-CWP1-MOH"
"unit_string"="g"  "Waveform" "BOP5-CWP1-MOH"
"NI_CM_Dt"="9.7656250000E-5"  "Waveform" "BOP5-CWP1-MOH"
"NI_CM_Speed"="505"  "Waveform" "BOP5-CWP1-MOH"
"wf_xvalues"="none"  "Waveform" Out of bounds array index
"wf_start_time"={2017-03-30 14:59:24}  "Waveform" "BOP5-CWP1-MOH"
"wf_start_offset"=0.0  "Waveform" "BOP5-CWP1-MOH"
"wf_increment"=0.00009769999999999999  "Waveform" "BOP5-CWP1-MOH"
"wf_samples"=81920  "Waveform" "BOP5-CWP1-MOH"
"RMS_g"=0.0040556330819473546  "Waveform" "BOP5-CWP1-MOH"
"Peak~Peak_g"=0.023956298828125  "Waveform" "BOP5-CWP1-MOH"
"CrestFactor_g~g"=3.6197414292238372  "Waveform" "BOP5-CWP1-MOH"
"HighFrequency_grms"=0.0011031509254603251  "Waveform" "BOP5-CWP1-MOH"
"TruePeak_g"=0.014680343088455594  "Waveform" "BOP5-CWP1-MOH"
"DerivedPeak_g"=0.0057355313084989428  "Waveform" "BOP5-CWP1-MOH"
"TruePeak_ips"=0.022817510920429478  "Waveform" "BOP5-CWP1-MOH"
"DerivedPeak_ips"=0.010223429951643482  "Waveform" "BOP5-CWP1-MOH"
"~1xMagnitude_ipspeak"=0.0030968335398627546  "Waveform" "BOP5-CWP1-MOH"
"~2xMagnitude_ipspeak"=0.00042457538246915184  "Waveform" "BOP5-CWP1-MOH"
"Subsynchronous_ipspeak"=0.0086347027651816777  "Waveform" "BOP5-CWP1-MOH"
"Peak~Peak_mil"=0.23272358626127243  "Waveform" "BOP5-CWP1-MOH"

Reduced metadata exposed in channel properties:

Group Properties: Waveform
   Waveform.description: 
   Channel: Waveform.BOP5-CWP1-MOH
       Waveform.BOP5-CWP1-MOH.wf_start_time: 2017-03-30 14:59:24
       Waveform.BOP5-CWP1-MOH.wf_start_offset: 0
       Waveform.BOP5-CWP1-MOH.wf_increment: 9.77E-05
       Waveform.BOP5-CWP1-MOH.wf_samples: 81920
THAT IS ALL OF THEM!

**Comment by mikeobrien** [comment]
Thx for the feedback. Unfortunately I'm pretty swamped with other projects right now so won't be able to address this. If you're interested in submitting a PR that would be awesome.

**Comment by DEIbb** [comment]
I am swamped at the moment too but I did do a workaround that may be incorrect but worked for my purposes since my application is searching for particular channel properties.  If I ever determine the actual problem then I will submit the changes.   Thank you for providing a library without COM registration.

  public File Open()
        {
            var reader = new Reader(_stream.Value);
            var metadata = LoadMetadata(reader).ToList();
            LoadFile(metadata);
            LoadGroups(Groups, metadata);
            LoadChannels(Groups, metadata, reader);


            foreach (var m in metadata)
            {
                var nPath = m.Path == null ? 0 : m.Path.Length;
                switch (nPath)
                {
                    case 0:
                        //this.Properties[]
                        break;
                    case 1:
                        break;
                    case 2:
                        Group g;
                        Channel c;
                        if( this.Groups.TryGetValue(m.Path[0], out g) && null!=g )
                            if (g.Channels.TryGetValue(m.Path[1], out c) && null != c)
                            {
                                var cp = c.Properties;
                                foreach (var mp in m.Properties)
                                    if( !cp.ContainsKey(mp.Key) )
                                        cp[mp.Key] = mp.Value;
                            }
                        break;
                }
            }

**Comment by dylanmeysmans** [comment]
@DEIbb Did you ever figure out the problem? If not, please provide me with a TDMS file with which you experience this issue. I have not been able to reproduce it with the TDMS files I encounter: all properties are read properly.
