### ISSUE TITLE
Reading .TDMS files that possess a time interval/duration

### ISSUE THREAD

**Issue by amcsa** [mikeobrien/TDMSReader#20]
This component works fine except for those files which use a set duration or time interval. I only get the wf_sample values, not the whole length values.

This is the code I'm using to create an excel file with the values of the TDMS file:

foreach (var group in tdms)
{
	int column = 0;
	string sheetName = group.Name;
	ExcelWorksheet ws = pck.Workbook.Worksheets.Add(sheetName);
	foreach (var channel in group)
	{
		int row = 1;
		column++;
		ws.Cells[row, column].Value = channel.Name;
		ws.Cells[row, column].Style.Font.Bold = true;

		foreach (var valueData in channel.GetData<object>())
		{
			row++;
			ws.Cells[row, column].Value = valueData;
		}
	}
}

Could you please help me? I have attached a sample file.

Thaqnk you so much.
Asier

[RUN_UP14_06_2018_20_37.zip](https://github.com/mikeobrien/TDMSReader/files/2266662/RUN_UP14_06_2018_20_37.zip)

**Comment by mikeobrien** [comment]
Unfortunately I'm pretty slammed right now and won't be able to look into this at the moment. :( If you want to take a stab at fixing it, I would welcome a PR. Thx!

**Comment by amcsa** [comment]
Hello Mike,

I'm using your TDMS reader to extract information from several measurements made with Labview and I'm so happy with it... But now our engineers have started to use duration intervals and this is not working any more, as I can't get the whole length of the values. I only get wf_sample values.

It's a pity you can't continue with the project as you have done an enormous work that it so useful for us. Unfortunately, I don't think I have the knowledge to fix the problem.

Anyway, I understand that you are too busy and I thank you so much for your effort and great work.

Best regards.

Thank yo

**Comment by illishar** [comment]
I'm not fully sure about the extend of your problem, but the old code had a truncate error in the timestamp code. I've made a PR with a fix.

**Comment by mikeobrien** [comment]
K, just pushed, v3.0.27

**Comment by mikeobrien** [comment]
Opps, let me know if this fixes it and I'll close. Thx!

**Comment by dylanmeysmans** [comment]
@amcsa Are you still experiencing this issue?
