### ISSUE TITLE
Double-precision floating point values read as single-precision

### ISSUE THREAD

**Issue by tayfunsezer** [mikeobrien/TDMSReader#27]
Hello,

Thank you for this great library!

Data-type of the value marked in the image is double / decimal however  it is being extracted as float by the library and this issue leads me to lose precision.  I have looked through source code and see that data-type is also stored as byte-data in the file so i am not sure if  there might be something done to fix this losing decimal precision issue. 

I wanted to ask that it if is possible to extract decimal value?
Another question is that, if the data is really stored as float, how DIADEM shows more digit on the fraction?

![1](https://user-images.githubusercontent.com/10044550/72346811-f46e6c00-36d6-11ea-88c3-8293cc23472e.PNG)

I tried to tweak library a bit with the following approach. I tried to call BinaryReader.ReadDouble() whenever i see data-type as float however this returned a totally different values since it read wider byte-range and it corrupted the last read position of the BinaryReader.

**Comment by dylanmeysmans** [comment]
@tayfunsezer Could you provide me with the TDMS file with which you experience this issue? Which application or library created the TDMS file in question?

**Comment by tayfunsezer** [comment]
Hello,

Data is produced via DIADEM program. Please find the sample TDMS file attached. (It is not the same file in the image, data is concealed.)

(https://github.com/mikeobrien/TDMSReader/files/4064862/test20200115_1143_time.zip)

**Comment by dylanmeysmans** [comment]
@tayfunsezer The `Time` channel you indicate in blue in DIAdem contains time stamps, not double-precision floating point values. [These time stamps](http://www.ni.com/product-documentation/7900/en/) are stored in TDMS files as a signed 64-bit integer representing the seconds sinds the epoch and an unsigned 64-bit integer representing the fraction of a second. The TDMSReader library reads both of these integers and converts them to an instance of [`DateTime`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime?view=netframework-4.8). As this data type's precision is 100 nanosecond ticks, anything less than 100 nanoseconds is rounded. Do you need this level of precision? From your data it seems your sample rate is only 1 Hz.

**Comment by tayfunsezer** [comment]
Ah, sorry for marking the wrong field. Please take the second column(F_SHIFT_Torque) into consideration. 

Here is the new screenshot of the file i shared with proper marking. 

![Capture - Copy](https://user-images.githubusercontent.com/10044550/72512637-7207b880-384c-11ea-98ee-dc730716e298.PNG)

Here is the rounded value in the VS debug mode.

![org](https://user-images.githubusercontent.com/10044550/72513350-43d6a880-384d-11ea-8f38-3be19fcb0d9c.png)

**Comment by dylanmeysmans** [comment]
@tayfunsezer The data types for all channels in your sample TDMS file except for the time channel are single-precision floating point values. They are read correctly by TDMSReader and the value you see for them in Visual Studio is also correct. DIAdem on the other hand casts these to double-precision floating point, creating the illusion of additional precision. If you would like a demonstration of this in C#, take a look at the following snippet:
```csharp
var path = @"test20200115_1143_time.tdms";
var file = new File(path);
file.Open();
var channel = file.Groups["High Sampling"].Channels["RTD_01"];
var data = channel.GetData<float>().ToArray();
Console.WriteLine((double)data[0]); // Outputs -241.76475524902344
```
As TDMSReader is behaving correctly, I am closing this issue.
