### ISSUE TITLE
Problem with Groups and Channels

### ISSUE THREAD

**Issue by amcsa** [mikeobrien/TDMSReader#5]
Hello,

I'm trying to use the TDMS reader in C# to read NI files, but I've got problems with the channels of a Group.

For Example, if I go to group "Mount1"  channel "1X Freq", the DLL tells me that the length is 2400. But the thing is that it should have 400 elements. The rest of the elements corresponds to the groups "Mount2", "Mount3" .... I don't know why they appear as elements of group "Mount1"

Could you please tell me if I'm doing something wrong?  If you'd like to, I'd have no problem in sending you the TDMS file I've used.

Thank you so much,

Asier Otamendi
asier@amcsa.es

![image](https://cloud.githubusercontent.com/assets/10881647/8746035/a3c8a3b6-2c85-11e5-9ab9-5c506081d9de.png)

**Comment by mikeobrien** [comment]
Sorry for the late reply. Unfortunately I'm really swamped so won't be able to look into this right now. When I get some time I can take a look. If you send me the file that would def help but unfortunately I can't give any estimates. :(

**Comment by amcsa** [comment]
Good morning Mike,

I very much appreciate your reply and would be very thankful if you could possibly have a look at the problem when you have time.

I have attached the sample TDMS file I have used for testing purposes.

Thank you so much,

­Asier Otamendi
IT department
Email : asier@amcsa.es<mailto:asier@amcsa.es>

AMC MECANOCAUCHO
Pol. Zona A – parc. 35
E-20159 Asteasu (Spain)
Tel:   +34943696102
Fax:  +34943696219
www.mecanocaucho.com<http://www.mecanocaucho.com/>
www.akustik.com<http://www.akustik.com/>

De: mikeobrien [mailto:notifications@github.com]
Enviado el: miércoles, 22 de julio de 2015 0:54
Para: mikeobrien/TDMSReader
CC: Asier Otamendi
Asunto: Re: [TDMSReader] Problem with Groups and Channels (#5)


Sorry for the late reply. Unfortunately I'm really swamped so won't be able to look into this right now. When I get some time I can take a look. If you send me the file that would def help but unfortunately I can't give any estimates. :(

**Comment by tommyja** [comment]
I think my last commit fixed the issue here. I superficially tested it on some files I got from amcsa.

commit 3e964be3e40eeaa6737b503161a046a87ee47bf3
Fixed null reference exception in complex file
Fixed grouping of channels with same channel name in multiple groups

**Comment by mikeobrien** [comment]
Awesome, thx! Will close for now, feel free to reopen if it doesn't fix it.
