### ISSUE TITLE
"System.ArgumentException"  (An item with the same key has already been added)

### ISSUE THREAD

**Issue by mwane1989** [mikeobrien/TDMSReader#9]
Hi,
When trying to open a tdms files, the reader throws an exception of type "System.ArgumentException" occurred in mscorlib.dll.

Additional information: An item with the same key has already been added.

Error occurs in the Open() operation:

var tdms = new NationalInstruments.Tdms.File(filePath);
tdms.Open();

I'm not sure how "Open()" could be some sort of duplicate. Any ideas on fixing this error?

**Comment by tommyja** [comment]
If you post the file, I can have a look at it.

**Comment by mwane1989** [comment]
The _Sample.tdms_ works fine 
[Sample.zip](https://github.com/mikeobrien/TDMSReader/files/178166/Sample.zip)
[Recordings.zip](https://github.com/mikeobrien/TDMSReader/files/178148/Recordings.zip)

**Comment by tommyja** [comment]
I have made a pull request for the fix.
Does anybody know an easy way of creating small tdms files for testing the reader?
The posted Recordings.tdms is a bit big for using in a test for a very spesific issue. The test file I made from another file with a hex editor does not have the exact same issue.

**Comment by mwane1989** [comment]
Thank you @tommyja . I'm now able to read the my tdms file.

**Comment by mwane1989** [comment]
@tommyja you could probably find a small labview example vi (program) online.
I found this .exe online, but you would have to download the labview runtime 32bit in order to run it.
[TDMS-writer.zip](https://github.com/mikeobrien/TDMSReader/files/184377/TDMS-writer.zip)
